    
    package  com.warehouse.controllers;

import  com.warehouse.services.WarehouseService ;
import com.warehouse.models.Product;
  import java.util.Date;
import java.util.List ;


public class ProductController {
    private WarehouseService  warehouseService ;
    
    public ProductController() {
        this.warehouseService = new WarehouseService();
    }
    
    public List<Product>  getAllProducts()  
    {
        return  warehouseService.getAllProducts() ;
    }
    
    public List<Product> getProductsByCategory(String category) {
        if (category == null ||  category.trim().isEmpty()) {
            throw new IllegalArgumentException(" Empty Category");
        }
        return warehouseService.getProductsByCategory(category);
    }
    
    public  boolean  addProduct(String name,  String category, int quantity, double price, Date expiryDate, int supplierId) {
        // Input validation
        if (name == null || name.trim().isEmpty() )
        {
            throw new IllegalArgumentException("Product name cannot be empty");
        }
        if (category == null || category.trim().isEmpty()) {
            throw new IllegalArgumentException("Category cannot be empty");
        }
        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative");
        }
        if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        if (supplierId <= 0) {
            throw new IllegalArgumentException("Supplier ID must be positive");
        }
        
        Product product = new Product(0, name, category, quantity, price, expiryDate, supplierId);
        return warehouseService.addProduct(product);
    }
    
    
    // Overload methods ...
     public boolean addProduct(String name, String category, int quantity, double price) {
        // Input validation
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Product name cannot be empty");
        }
        if (category == null || category.trim().isEmpty()) {
            throw new IllegalArgumentException("Category cannot be empty");
        }
        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative");
        }
        if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        
        try {
            // Create Product object (use default values for missing parameters)
            // - productId = 0 (will be auto-generated by database)
            // - expiryDate = null (no expiry date)
            // - supplierId = 1 (default supplier)
            Product product = new Product(0, name.trim(), category.trim(), quantity, price, null, 1);
            
            // Call service to save to database
            return warehouseService.addProduct(product);
            
        } catch (Exception e) {
            System.err.println("Error in ProductController.addProduct: " + e.getMessage());
            throw new RuntimeException("Failed to add product: " + e.getMessage(), e);
        }
    }
    
    public boolean updateProductStock(int productId, int newQuantity) {
        if (productId <= 0) {
            throw new IllegalArgumentException("Product ID must be positive");
        }
        if (newQuantity < 0) {
            throw new IllegalArgumentException("Stock quantity cannot be negative");
        }
        return warehouseService.updateProductStock(productId, newQuantity);
    }
    
    public Product getProductById(int productId) {
        if (productId <= 0) {
            throw new IllegalArgumentException("Product ID must be positive");
        }
        return warehouseService.getProductById(productId);
    }
     // Add these new methods for update and delete
    public boolean updateProduct(int productId, String name, String category, int quantity, double price, Date expiryDate, int supplierId) {
        if (productId <= 0) {
            throw new IllegalArgumentException("Product ID must be positive");
        }
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Product name cannot be empty");
        }
        if (category == null || category.trim().isEmpty()) {
            throw new IllegalArgumentException("Category cannot be empty");
        }
        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative");
        }
        if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        if (supplierId <= 0) {
            throw new IllegalArgumentException("Supplier ID must be positive");
        }
        
        Product product = new Product(productId, name, category, quantity, price, expiryDate, supplierId);
        return warehouseService.updateProduct(product);
    }
    
    public boolean deleteProduct(int productId) {
        if (productId <= 0) {
            throw new IllegalArgumentException("Product ID must be positive");
        }
        return warehouseService.deleteProduct(productId);
    }
}